### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShAdYShmr** [dekrypted/discord-image-logger#1]
The Error : 

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bindata = base64.b85decode(b'https://cdn.discordapp.com/attachments/980246115087712327/984577018723192902/unknown.png')
  File "/usr/lib/python3.8/base64.py", line 463, in b85decode
    raise ValueError('bad base85 character at position %d'
ValueError: bad base85 character at position 5

**Comment by solo750** [comment]
The error

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import httpx, base64, httpagentparser
ModuleNotFoundError: No module named 'httpx'

How do i fix this

**Comment by LocalsGitHub** [comment]
> The Error :
> 
> Traceback (most recent call last): File "main.py", line 7, in bindata = base64.b85decode(b'https://cdn.discordapp.com/attachments/980246115087712327/984577018723192902/unknown.png') File "/usr/lib/python3.8/base64.py", line 463, in b85decode raise ValueError('bad base85 character at position %d' ValueError: bad base85 character at position 5

that's not base58 lol that's a link...

**Comment by D2aRrK** [comment]
how to make it base58 ?

**Comment by dekrypted** [comment]
> > The Error :
> > Traceback (most recent call last): File "main.py", line 7, in bindata = base64.b85decode(b'https://cdn.discordapp.com/attachments/980246115087712327/984577018723192902/unknown.png') File "/usr/lib/python3.8/base64.py", line 463, in b85decode raise ValueError('bad base85 character at position %d' ValueError: bad base85 character at position 5
> 
> that's not base58 lol that's a link...

HI LOCAL! Huge fan :)

@ShAdYShmr I changed it so that you can just use a link now :D

Redownload the script and put in the same link

**Comment by Asitics** [comment]
pip install httpx LMAO just do
