### ISSUE TITLE
READ THIS

### ISSUE THREAD

**Issue by dekrypted** [dekrypted/discord-image-logger#11]
Working on Making this Easier to set up and making clear instructions. For the time being, to install:

- Download the Script and fill in the required info
- Get a web hosting service that supports Python API functions
- Use their tutorial to get the image grabber on your site as a working API

I personally use [Vercel](https://vercel.com) which has a nice documentation about [Python Serverless Functions](https://vercel.com/docs/runtimes#official-runtimes/python)

Because I'm busy, I will not be offering help setting this up. If this tutorial doesn't help you, maybe this isn't for you.

**Comment by refloexe** [comment]
your help sucks

**Comment by GLUR-DEV** [comment]
Hey man, I want to say I checked out your github and found that your 13!!!
I've been looking through your projects code and its crazy how talented you are.
Your going to achieve some really amazing stuff in your life with your talent man.
Keep it up

**Comment by dekrypted** [comment]
> Hey man, I want to say I checked out your github and found that your 13!!! I've been looking through your projects code and its crazy how talented you are. Your going to achieve some really amazing stuff in your life with your talent man. Keep it up

Thank you! :)

**Comment by yusef101** [comment]
hey Dekrypted, i was wondering if you have a discord because i would like to chat with you. I want you to make me a discord bot thats for image logging. I’ll pay for the bot if intended thanks!

**Comment by dekrypted** [comment]
DeKrypt#7536

**Comment by draco6664** [comment]
hello can u help me for image grabber or sent me video how to work it

**Comment by dekrypted** [comment]
nope

**Comment by draco6664** [comment]
do u sale any grab token for discord

**Comment by draco6664** [comment]
i want 1 grab token and my friend talk to me u are legit for this tool

**Comment by draco6664** [comment]
can u add me discord knownaas to talk here

**Comment by flyingcakes01** [comment]
> please shut the fuck up
lmao this draco kid sounds like an 8 yr old
also happy birthday dekrypt i realised u turned 15!

**Comment by flyingcakes01** [comment]
> do u sale any grab token for discord

do you sale please shut

**Comment by dekrypted** [comment]
> > please shut the fuck up
> 
> lmao this draco kid sounds like an 8 yr old also happy birthday dekrypt i realised u turned 15!

oh shit thx for the birthday wishes!!!

and yeah this kid is so desperate 💀

**Comment by flyingcakes01** [comment]
> hello can u help me for image grabber or sent me video how to work it

1. It does not work anymore i dont think the webhook will send the ip.

2.i am pretty sure that discord.py isnt supported anymore if it is used for the image logger

3. if u want an image logger use a HTML with Javascript code. 
https://github.com/flyingcakes01/Discord-IP-logger u can use this i tried making a vid but yt gave me a strike

**Comment by Apothesis** [comment]
Yo, running into issue with building on vercel. Followed steps in the video. Getting this error

![image](https://github.com/dekrypted/discord-image-logger/assets/166455169/69ca0d82-b27e-4675-a9c3-23859f85e22c)
