### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by monkeyrizz** [dekrypted/discord-image-logger#117]
guys whenever i open the py file it closes imediatly.

**Comment by dekrypted** [comment]
just like this issue!

**Comment by monkeyrizz** [comment]
> just like this issue!

can u help me on discord i screenshare whats ur discord?

**Comment by dekrypted** [comment]
sure its goaway

**Comment by monkeyrizz** [comment]
> goaway

added

**Comment by monkeyrizz** [comment]
> sure its goaway

my user is monkeydanceboy

**Comment by dekrypted** [comment]
bro this kid is retarded 💀

**Comment by monkeyrizz** [comment]
> bro this kid is retarded 💀

bro help me
