### ISSUE TITLE
rubbish

### ISSUE THREAD

**Issue by anzumcx** [dekrypted/discord-image-logger#119]
i looked into this thing its a remote access trojan, dont bother since its not worth it, why would u need this anyway

**Comment by dekrypted** [comment]
funny u didnt show any evidence that it is :)

**Comment by anzumcx** [comment]
funny that i downloaded this a while ago and i found the files with my cookies, browser history, passwords and a screenshot of my desktop (which showed me opening the file and my browser with this repository open), this was a complete accident and i was just navigating through my files when i found the folder with this information

**Comment by anzumcx** [comment]
its not a rat but it is a info stealer

**Comment by dekrypted** [comment]
i'm still not seeing any proof? lol, just u yapping. go somewhere else

**Comment by anzumcx** [comment]
im not yapping, and it wouldnt make sense for me to want to hate on a random person for no reason, im doing this only bcs i found a screenshot with this repo open while going thru files, and it was this exact account, and i dont want to say for certain, but i am pretty damn sure, obv i deleted the files for very obvious reasons and removed the malware

**Comment by anzumcx** [comment]
and ofc you'll know whether what i am saying is true or not, so if its not, sorry

**Comment by anzumcx** [comment]
have a good day not worth continuing

**Comment by dekrypted** [comment]
> have a good day not worth continuing

so you know you're wrong but don't wanna admit it? 😂

i have nothing to prove. its open source for a reason. u can look in all the code and u wont find anything malicious. also funny since you're not supposed to open the script but rather run it on a host.

but yeah, ur right, not worth continuing. thanks for proving my point, have a good day too!
