### ISSUE TITLE
isnt working

### ISSUE THREAD

**Issue by EmreParlakk** [dekrypted/discord-image-logger#12]
I'm sure I'm running it right, but it's not working, can you help?
actually you can make a tutorial video

**Comment by dekrypted** [comment]
How are you running it?

**Comment by waterisbluexd** [comment]
Same In vercel I deployed both files when I visit on dashboard and edit url /api/main.py and try to run, It just download main.py file and nothing else 
I'm sure webhook and img url added correctly in main.py and also installed requirement.txt 🤔
