### ISSUE TITLE
Vercel serverless complication problem

### ISSUE THREAD

**Issue by Cr7pt0nic** [dekrypted/discord-image-logger#21]
Hi I've been trying to implement this in vercel.app using the serverless functions and I cannot seem to know how to implement the serverless functions to interact with the main.py script as an API. When deploying the domain and going to /main.py it allows me to immediately download the file but not execute it as an API. Any solution for this?

**Comment by dekrypted** [comment]
Hi!

Firstly, APIs need to be in the /api/ route. So you'd want the page to look something like this: yourwebsite.com/api/main

So, in your GitHub repo, you can click the edit button on the file and put an `api/` before the file name to move it to the proper directory.

Hope this helps! Please reply if you need more help.
