### ISSUE TITLE
Hey Bro Discord Image Logger Problem 

### ISSUE THREAD

**Issue by JavorR1** [dekrypted/discord-image-logger#22]
This is what I get when I type in CMD py main.py
line 3, in <module>
import requests, base64, httpagentparser
ModuleNotFoundError: No module named 'requests'

I installed the requirements.txt

**Comment by dekrypted** [comment]
READ THE README OH MY GOD

**Comment by JavorR1** [comment]
I do not understand

**Comment by unusually-calm** [comment]
go to cmd and do "pip install requests"
