### ISSUE TITLE
[REQUEST] MAKE A TUTORIAL VIDEO

### ISSUE THREAD

**Issue by DevProdj** [dekrypted/discord-image-logger#26]
**MAKE A TUTORIAL VIDEO**

**Comment by xrs10s** [comment]
it doesnt work you dumbass its obvious now you can literally get a one click logger with 13 lines of basic code

**Comment by dekrypted** [comment]
> it doesnt work you dumbass its obvious now you can literally get a one click logger with 13 lines of basic code

I literally say it's NOT a one click in the readme u have to be trolling theres no way ur actually this dumb

**Comment by xrs10s** [comment]
nice try lol

**Comment by DevProdj** [comment]
lol im still waiting for a response

**Comment by waterisbluexd** [comment]
> lol im still waiting for a response

There is vid on Yt showing how to do it correctly still for me it's not working

**Comment by dekrypted** [comment]
> > lol im still waiting for a response
> 
> There is vid on Yt showing how to do it correctly still for me it's not working

wait what link it

**Comment by waterisbluexd** [comment]
> > > lol im still waiting for a response
> > 
> > 
> > There is vid on Yt showing how to do it correctly still for me it's not working
> 
> wait what link it

https://youtu.be/yPXeYPu8y58

**Comment by dekrypted** [comment]
ill make an official one soon :)
