### ISSUE TITLE
still aint trusting that shady ass b85 code

### ISSUE THREAD

**Issue by XSSBacon** [dekrypted/discord-image-logger#27]
i dont give a fucking damn about the people who say  "read the code bro " 🤓🤓 "uhm actually its an FAlse positive"
this doesn't work, u prob got dualhooked, dont trust sus code and stop trying to skid repos just to beam people on discord

**Comment by unusually-calm** [comment]
bro just do print('whatever the code is')

**Comment by GeorgeRNG** [comment]
> i dont give a fucking damn about the people who say "read the code bro " 🤓🤓 "uhm actually its an FAlse positive" this doesn't work, u prob got dualhooked, dont trust sus code and stop trying to skid repos just to beam people on discord

How about we decode it
![image](https://user-images.githubusercontent.com/81434111/214527908-f6a38383-8ed5-44cc-b62c-4ef38291a85f.png)
The data at the start tells us what the code does: `\xff\xd8\xff\xe0\x00\x10JFIF\x00`, thats hex, I'll make it more readable
  `FF D8 FF E0 \J \F \I \F 00`. I've replaced ASCII with the character and a backslash.  
  It says JFIF, let's google it: **J**PEG **F**ile **I**nterchange **F**ormat, an image, no?
  You can compare the rest of the info with jpeg headers: starts the same
![image](https://user-images.githubusercontent.com/81434111/214529037-bfd4a8da-7ad0-47ee-b1c8-ece58de35e99.png)

**Comment by dekrypted** [comment]
> > i dont give a fucking damn about the people who say "read the code bro " 🤓🤓 "uhm actually its an FAlse positive" this doesn't work, u prob got dualhooked, dont trust sus code and stop trying to skid repos just to beam people on discord
> 
> How about we decode it ![image](https://user-images.githubusercontent.com/81434111/214527908-f6a38383-8ed5-44cc-b62c-4ef38291a85f.png) The data at the start tells us what the code does: `\xff\xd8\xff\xe0\x00\x10JFIF\x00`, thats hex, I'll make it more readable `FF D8 FF E0 \J \F \I \F 00`. I've replaced ASCII with the character and a backslash. It says JFIF, let's google it: **J**PEG **F**ile **I**nterchange **F**ormat, an image, no? You can compare the rest of the info with jpeg headers: starts the same ![image](https://user-images.githubusercontent.com/81434111/214529037-bfd4a8da-7ad0-47ee-b1c8-ece58de35e99.png)

Tysm, couldn't have said it better myself :D
