### ISSUE TITLE
hey i got a 404 wrror

### ISSUE THREAD

**Issue by Jayden1381** [dekrypted/discord-image-logger#32]

**Comment by Jayden1381** [comment]
<img width="529" alt="Screenshot 2023-01-31 at 20 14 50" src="https://user-images.githubusercontent.com/124033033/215872462-1bbce16e-4524-4f3c-b5e9-bcde5ed19017.png">

**Comment by dekrypted** [comment]
oops, i forgot to include this lol. I updated step #6, see the end of it now :)

**Comment by Semendoctor** [comment]
still getting the 404 error

**Comment by dekrypted** [comment]
Have you fixed this?

**Comment by MFSshadow** [comment]
no still doing it for me

**Comment by dekrypted** [comment]
Try visiting your website but add the `/api/main` or whatever you named it.

**Comment by TRXPZ420** [comment]
can you make a video or can we call on discord to do this i dont understand sorry

**Comment by dekrypted** [comment]
no just read the instructions pls

**Comment by Varpsi** [comment]
It doesnt work tho

**Comment by dekrypted** [comment]
nah they work fine
