### ISSUE TITLE
image Logger - link send spam

### ISSUE THREAD

**Issue by Zwergninja007** [dekrypted/discord-image-logger#37]
![Screenshot 2023-02-06 155109](https://user-images.githubusercontent.com/115697042/217003946-93eb8104-c3f2-49e6-85b3-b7bb901a3b4a.png)

why does it spam this how can i do this that the real ip from other guys is in a seperate channel?

**Comment by dekrypted** [comment]
idk exactly but i think the hidden image like makes bots try to fetch it multiple times
