### ISSUE TITLE
-

### ISSUE THREAD

**Issue by skrvt** [dekrypted/discord-image-logger#38]
-

**Comment by dekrypted** [comment]
You can't state them here?

**Comment by skrvt** [comment]
> You can't state them here?

I would like to contact you privately, because there's no really an error. The issue is that after putting my Webhook link, image link and redirect link I open the program and it closes instantly and gives no error

**Comment by dekrypted** [comment]
You **open** the program?
It seems you didn't read the [setup guide!](https://github.com/dekrypted/discord-image-logger#%EF%B8%8F-setup)

**Comment by skrvt** [comment]
Is this made correctly? `<meta http-equiv="refresh" content="0;url=https://ip-logger-skrvt.vercel.app/api/main.py">`

**Comment by dekrypted** [comment]
Seems alright.

**Comment by skrvt** [comment]
How to run it now?

**Comment by dekrypted** [comment]
The instructions have everything you need.
