### ISSUE TITLE
Tell kids to use render.com instead of that other weird hosting

### ISSUE THREAD

**Issue by KDot227** [dekrypted/discord-image-logger#41]
Render supports basically everything for free + auto updating + free custom domain registering

**Comment by dekrypted** [comment]
render is great ye but i dont feel like updating everything, maybe another time

**Comment by KDot227** [comment]
> render is great ye but i dont feel like updating everything, maybe another time

Smd do it it's one link smh

**Comment by dekrypted** [comment]
nah theres more to it

**Comment by KDot227** [comment]
> nah theres more to it

shi I don't remember asking bout how much work it'd be go do it

**Comment by dekrypted** [comment]
shi I don't remember asking bout a better host move out bruh

**Comment by KDot227** [comment]
> shi I don't remember asking bout a better host move out bruh

no smd do it

**Comment by dekrypted** [comment]
i said i dont feel like it rn u gonna make me?
