### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PR0VICIDE** [dekrypted/discord-image-logger#42]
This isnt really an issue but I couldn't find another way to contact you so.
I was wondering what link do i copy when it "creates one" for me cause all i see is this 
![image](https://user-images.githubusercontent.com/114034723/220874995-7978bf31-ad91-4dd2-b928-8389011fa9bd.png)

**Comment by dekrypted** [comment]
You should visit the main vercel dashboard @ https://vercel.com/dashboard and find your project. Click on it and choose one of the domains listed.

**Comment by PR0VICIDE** [comment]
do i just copy a image link from discord and paste it into main.py

**Comment by PR0VICIDE** [comment]
> You should visit the main vercel dashboard @ https://vercel.com/dashboard and find your project. Click on it and choose one of the domains listed.

i did that but when i try and find the actual ip grabber image i cant

**Comment by dekrypted** [comment]
Do the URL + /api/image
