### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by armaanbrar14** [dekrypted/discord-image-logger#48]
I am seeing a 404 error on vercel

I have all the code already done. I created the api folder and added both files. After importing it, it showed for a 404 error. The only thing that I think may have caused this is a bad image, or me only filling out the IMAGE and WEBHOOK on the main.py file. 

Please and thank you.

![Screenshot_20230226_042701](https://user-images.githubusercontent.com/122327756/221438479-473e7343-6257-4b44-8056-0b000e92d7e8.png)
![Screenshot_20230226_042745](https://user-images.githubusercontent.com/122327756/221438480-25f8314e-a04a-4ed0-a06f-1bce0ca6d1ad.png)

**Desktop**
 - OS: Windows
 - Browser: Chrome
 
 Building Logs:
 <html>
<body>

Running build in Cleveland, USA (East) – cle1
--
16:18:41.342 | Cloning github.com/armaanbrar14/help (Branch: main, Commit: e92702e)
16:18:41.596 | Previous build cache not available
16:18:41.853 | Cloning completed: 511.995ms
16:18:41.927 | Running "vercel build"
16:18:42.359 | Vercel CLI 28.16.6
16:18:42.515 | Installing required dependencies...
16:18:45.377 | Build Completed in /vercel/output [3s]
16:18:48.618 | Generated build outputs:
16:18:48.618 | - Static files: 0
16:18:48.618 | - Prerenders: 0
16:18:48.618 | - Serverless Functions: 1
16:18:48.618 | - Edge Functions: 0
16:18:48.618 | Serverless regions: Washington, D.C., USA
16:18:48.618 | Deployed outputs in 2s
16:18:48.900 | Build completed. Populating build cache...
16:18:49.712 | Uploading build cache [29.00 B]...
16:18:50.041 | Build cache uploaded: 328.268ms

</body>
</html>

Website: [https://help-blue.vercel.app/](url) (Of course, i get if you dont wanna press it)

**Comment by dekrypted** [comment]
Hello!

It seems you didn't read the end of step 6 - Append "api/main" to your URL!

**Comment by armaanbrar14** [comment]
Thank you so much bro, I love your work!

**Comment by dekrypted** [comment]
No problem :)
