### ISSUE TITLE
Potentially Dangerous Download

### ISSUE THREAD

**Issue by armaanbrar14** [dekrypted/discord-image-logger#50]
It shows potentially dangerous download, how would i fix it if possible

**Comment by dekrypted** [comment]
?

**Comment by armaanbrar14** [comment]
whenever i put it in discord and try to open it, it shows as potentially dangerous download. idk why
![Screenshot 2023-03-01 191339](https://user-images.githubusercontent.com/122327756/222296581-beb04545-ad32-4cdf-bf36-f91248f908cf.png)
![Screenshot 2023-03-01 191330](https://user-images.githubusercontent.com/122327756/222296583-690148e7-43d0-4078-b83a-8dee19d8cf7c.png)

**Comment by dekrypted** [comment]
thats strange... doesnt happen for me...

what message are you sending? perhaps its becoming a download not a link?

you can add me on discord DeKrypt#7536 and show me!

**Comment by vinscripts** [comment]
you probally added .py at the end
