### ISSUE TITLE
hi can you please make a yt vid its to confusting

### ISSUE THREAD

**Issue by Corey476** [dekrypted/discord-image-logger#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dekrypted** [comment]
its not confusing its actually really easy to comprehend

**Comment by Corey476** [comment]
hi well i have completeed it all but dont know how to download it

**Comment by Corey476** [comment]
i have got up to here https://vercel.com/corey476/immage-loggerv3-m2pe
