### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Memedew** [dekrypted/discord-image-logger#58]
Why would you encrypt an image?? that 

binaries = {
    "loading": base64.b85decode(b'|JeWF01!$>Nk#wx0RaF=07w7;|JwjV0RR90|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|Nq+nLjnK)|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsBO01*fQ-~r$R0TBQK5di}c0sq7R6aWDL00000000000000000030!~hfl0RR910000000000000000RP$m3<CiG0uTcb00031000000000000000000000000000')
    # This IS NOT a rat or virus, it's just a loading image. (Made by me! :D)
    # If you don't trust it, read the code or don't use this at all. Please don't make an issue claiming it's duahooked or malicious.
    # You can look at the below snippet, which simply serves those bytes to any client that is suspected to be a Discord crawler.

**Comment by RealPacket** [comment]
the output is actually a JPEG image.

**Comment by dekrypted** [comment]
Firstly, it's **encoding**, not encrypting.

Second, base85 allows you to convert binary data to ASCII text data which can be put within the script.
If you are too sped to read the code and don't trust it, don't use it. idc.
