### ISSUE TITLE
Serverless function vercel

### ISSUE THREAD

**Issue by Xeoolol** [dekrypted/discord-image-logger#59]
![image](https://user-images.githubusercontent.com/71578081/234115653-84552c53-49c5-43ab-a0e3-8d6297c95ea4.png)
Serverless function crashing on vercel, I dmed u this on discord but idk if you got termed or not if so add me back

**Comment by dekrypted** [comment]
look at the error logs

**Comment by totallyrandom001** [comment]
happened to me too

LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] RemoteDisconnected: Remote end closed connection without response
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 67, in vc_handler
    res = conn.getresponse()
  File "/var/lang/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/var/lang/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/var/lang/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
