### ISSUE TITLE
Niggers

### ISSUE THREAD

**Issue by Cat-Manner** [dekrypted/discord-image-logger#63]
I put the new Forgi's on the G
I trap until the bloody bottoms is underneath
'Cause all my niggas got it out the streets
I keep a hunnid racks, inside my jeans
I remember hittin' the mall with the whole team
Now a nigga can't answer calls 'cause I'm ballin'
I was wakin' up gettin' racks in the mornin'
I was broke now I'm rich, these niggas salty
All this designer on my body got me drip, drip (ayy)
Straight up out the Yajects, I'm a big Crip
If I got a pint of lean, I'ma sip, sip
I run the racks up with my queen, like London and Nip
But I got rich on all these niggas, I didn't forget, bet
I had to go through the struggle, I didn't forget that
I hopped inside of the Maybach and now I can sit back
These bitches know me now, 'cause I got them big racks
'Cause I'm gettin' money now, I know you heard that
Young nigga on the corner, bitch, I had to serve crack
Uncle fronted me some P's had to get them birds back
We came up on dirty money, I gave it a bird bath
Cut off the brain and I give my bitch a new coupe
Either you frontin' Yah Gang or ya SuWoop
Got a New Orleans bitch and man that pussy voodoo
And I'm that nigga now, who knew?
I put the new Forgi's on the G
I trap until the bloody bottoms is underneath
'Cause all my niggas got it out the streets
I keep a hunnid racks, inside my jeans
I remember hittin' the mall with the whole team
Now a nigga can't answer calls 'cause I'm ballin'
I was wakin' up gettin' racks in the mornin'
I was broke now I'm rich, these niggas salty
I been wakin' up to get the money, whoa, whoa
Got a bad bitch, her ass tatted, whoa, whoa
Givenchy to my toes, two twins, I'm fuckin' 'em both
I put in a new AP, the water like a boat
I was down bad on my dick, where was you niggas at?
I know you turned your back on me, just to get some racks
I seen you swerve back, 'cause I'm in the black 'Bach
New diamonds on me, fuck a flash, this ain't SnapChat
'Cause I been gettin' paid
Yellow diamonds on me look like lemonade
Got my baby mama that new Bentayga
Tryna get the dough, Joe, like a sensei, yeah
Rolls Royce umbrellas when I'm in the rain
I just mind my business
I got brothers that did the time, I ain't kiddin'
All these rappers just talk about it, I live it
Goin' up, I ain't got no sky limit, yeah, yeah, yeah
I put the new Forgi's on the G
I trap until the bloody bottoms is underneath
'Cause all my niggas got it out the streets
I keep a hunnid racks, inside my jeans
I remember hittin' the mall with the whole team
Now a nigga can't answer calls 'cause I'm ballin'
I was wakin' up gettin' racks in the mornin'
I was broke now I'm rich, these niggas salty
I, ayy, yeah
I've been ballin' lil' nigga
Now watch me ball on these niggas
Yeah, now watch me ball on these niggas, yeah
Now watch me ball on these niggas
Now watch me ball on these niggas, yeah, yeah

**Comment by dekrypted** [comment]
he is balling ing
