### ISSUE TITLE
image infinite loading when sent through discord

### ISSUE THREAD

**Issue by clipzz0** [dekrypted/discord-image-logger#66]
when you open the link through your browser it works fine and logs the ip address to the webhook but if you send the link through discord without the .py at the end you get a infinite loading animation and when you click on it it doesnt log anything its just loading.

is there a possible fix for this issue?

**Comment by dekrypted** [comment]
are u dumb like fr

**Comment by clipzz0** [comment]
?? it also doesnt work when u click it and on ios phone it shows grey still image

**Comment by dekrypted** [comment]
yeah i know dat kinda unfixable

**Comment by clipzz0** [comment]
so this image ip logger nolonger works?

**Comment by dekrypted** [comment]
it does are u retarded when did i say it didnt

**Comment by clipzz0** [comment]
chill bro u dont need to swear but u said its unfixable so i can no logger ip log someone by the image bcs the image it self doesnt even load

**Comment by dekrypted** [comment]
this kid is actually so fuckign stupid look at the config
