### ISSUE TITLE
Not providing output

### ISSUE THREAD

**Issue by Penguinlover7578** [dekrypted/discord-image-logger#67]
Hey DeKrypt your very in coding talented and could probably help me out with this inconvenience. 
Would be much appreciated.
It's not providing an output of their information once they click it.
Constantly spamming the same message which is in expected behavior.
I've redone the tutorial over and over again.
I'm on edge and win 11.
I extracted it on my desktop
To edit the "main.py" I double clicked on it and used the text editor notepad

**To Reproduce**
1. Go to 'Your server with the image logging bot'
2. Have a friend click on ''your image logger"
3. Scroll down very far down in your server with the bot because of the constant spamming messages.
4. See error of it not sending you their details.

**Expected behavior**
Expected when clicked to actually not send me anything.
Only just telling me the input of saying..
Image logger- link sent
An Image Logging link was sent in a chat!
You may receive an IP soon.
Endpoint: api/myapi
IP: my ip
Platform: discord

Side Note: 
On the stream Video Games + Talking to Chat [2K]
On the Date: 6/24/23
On stream how did you lose to that one guy, he totally didn't even toggle 5 block.
He's the definition of legit.

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
