### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DorixPlayz** [dekrypted/discord-image-logger#69]
Whenever I go to Vercel and press new project and stuff like that it never finds my Git Repository and I'm stuck not knowing what to do please help me.

My Discord : Dorix#8528

**Comment by Wild-Chicken** [comment]
my man is lucky
![image](https://github.com/dekrypted/discord-image-logger/assets/96213936/cc26fb51-c6ad-445d-ba09-8b22804ff94f)

also i sent u a frien req on discord

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
