### ISSUE TITLE
Not exactly a error

### ISSUE THREAD

**Issue by Yannis0255** [dekrypted/discord-image-logger#71]
**Describe the bug**

**To Reproduce**
1. Go to 'the channal you made your webhook on'
2. Click on 'enter by Brower on photo vercel made' (also include api/hotdog)
3. Re-enter the channal to see 'the thing that it have been sent, but like not even the "it has sent" message isn't sent every time, the bot just sends it when he wants ig'
4. Result, no ip even with the browser.

**Expected behavior**
Expected to send the ip

**Screenshots**
No need.

**Smartphone (please complete the following information):**
 - Device: Samsung Note 20 [e.g. iPhone6]
 - OS: One UI 5.1 [e.g. iOS8.1]
 - Browser: Google chrome [e.g. stock browser, safari]
 - Version Android 13[e.g. 22]

**Additional context**
In case anyone responds to my issue, my user is "aquamaryn" Please and thank you!

**Comment by imuuid** [comment]
because it's a rat lol

**Comment by dekrypted** [comment]
its cause you did it wrong. follow the tutorial.

**Comment by LemmeDribble** [comment]
> its cause you did it wrong. follow the tutorial.

i did everything right but it just sends the link instead of an image
