### ISSUE TITLE
Not providing location

### ISSUE THREAD

**Issue by Garkata** [dekrypted/discord-image-logger#74]
**Describe the bug**
Unable to provide location, even if its approximate. It provides my location.

**To Reproduce**
1. Js do it like ur the victim and check the log

**Expected behavior**
To see the victims location

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
