### ISSUE TITLE
Need help in bypassing ssl of Facebook 

### ISSUE THREAD

**Issue by TEAM-RXN** [dekrypted/discord-image-logger#75]
**Describe the bug**
Need help in Bypassing ssl of Facebook 

**To Reproduce**
1. When I do that Frida last command that says timeout reached everytine

Is there anyway to contact you?

**Comment by dekrypted** [comment]
Frida last command? Dude what?

**Comment by TEAM-RXN** [comment]
I want help in bypassing ssl of Facebook could you help me 💜
Is there anyway so I can contact you
