### ISSUE TITLE
Spams channel after sending the image link with IPs

### ISSUE THREAD

**Issue by iGetUploaded** [dekrypted/discord-image-logger#76]
**Describe the bug**

**Expected behavior**
Watched the tutorial video and at the 9:46 is when the channel is getting spammed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Anyway to stop the spam?

**Comment by Wild-Chicken** [comment]
i have the same problem too.
