### ISSUE TITLE
Not completed

### ISSUE THREAD

**Issue by Protogen010** [dekrypted/discord-image-logger#86]
**Describe the bug**
yt tut vs what u say on  git hub big diferrence + i cant save main.py in the zip folder cuz it dosent show it and sends me to system 32 bruh

**Additional context**
Good luck

**Comment by RBLX-Scripts** [comment]
0 percent of what you said makes any sense

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
