### ISSUE TITLE
It doesnt work properly 

### ISSUE THREAD

**Issue by SeaTurtle176** [dekrypted/discord-image-logger#87]
It only logs bots
![Screenshot 2023-08-31 134624](https://github.com/dekrypted/discord-image-logger/assets/142609938/a25bff40-a1ec-4411-afd1-41a57417c86a)

**Comment by SeaTurtle176** [comment]
Tho annoying my friends with it is fun

**Comment by RBLX-Scripts** [comment]
it does work

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
