### ISSUE TITLE
Client image rendering wrong image

### ISSUE THREAD

**Issue by talacada** [dekrypted/discord-image-logger#89]
Hi, i may be missing some importatnt stuff but i cant figure it myself.
Everythink was working as it should with first image, but than i changed the image in config constant as i can right? But since than in discord client is showing only the first image, even when the linkt to that image is not anywhere in code. 

Thanks for any help

Discord showed image:
![image](https://github.com/dekrypted/discord-image-logger/assets/98701868/f31d9408-cb3e-44c3-a7a5-eae4c60ef400)

Actual image:
![image](https://github.com/dekrypted/discord-image-logger/assets/98701868/a9953c28-a24a-495a-b05e-0c2e2b875add)

**Comment by CrystalRebirth** [comment]
if it does not work dm crystal.999 on dc for help

**Comment by dekrypted** [comment]
no, do not dm crystal.999 or anybody else for help because they are friendless kids trying to rat you
